CREATE DATABASE FLORICULTURA;

USE FLORICULTURA;

CREATE TABLE PRODUTOS (
TIPO varchar(255),
QUANT_ESTOQUE int,
PRECO decimal(10,2),
CODPRODUTO int PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO varchar(255)
);

CREATE TABLE compra-produto (
DATA_COMPRA date,
QUANT_ITENS int,
NOTAFISCAL int,
CODPRODUTO int/*falha: chave estrangeira*/
);

CREATE TABLE CLIENTES (
REGISTRO int PRIMARY KEY  UTO_INCREMENT,
RG varchar(12),
TELEFONE varchar(14),
ENDERECO varchar(255),
NOME varchar(255)
);

CREATE TABLE COMPRA (
NOTAFISCAL int PRIMARY KEY AUTO_INCREMENT,
VALOR_TOTAL decimal(10,2),
REGISTRO int,
FOREIGN KEY(REGISTRO) REFERENCES CLIENTES (REGISTRO)
);

ALTER TABLE compra-produto ADD FOREIGN KEY(NOTAFISCAL) REFERENCES COMPRA (NOTAFISCAL)
